-- FIX: Expand Column Widths for Address Fields
-- Run this in SSMS

USE TaspenOnboardingMerchantDB;
GO

PRINT 'Altering T_ONBOARDING_MERCHANT columns...';

-- 1. ALTER Owner Address Columns
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN KELURAHAN_ID VARCHAR(100);
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN KECAMATAN_ID VARCHAR(100);
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN KOTA_ID VARCHAR(100);
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN PROVINSI_ID VARCHAR(100);

-- 2. ALTER Merchant Address Columns
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN KELURAHAN_MERCHANT VARCHAR(100);
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN KECAMATAN_MERCHANT VARCHAR(100);
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN KOTA_MERCHANT VARCHAR(100);
ALTER TABLE T_ONBOARDING_MERCHANT ALTER COLUMN PROVINSI_MERCHANT VARCHAR(100);

PRINT 'Columns expanded to VARCHAR(100) successfully.';
GO
