USE TaspenOnboardingMerchantDB;
GO

-- Script: alter_step2_refinement.sql
-- Purpose: Add/Modify columns for Step 2 "Data Usaha" refinement
-- Changes:
-- 1. PAMERAN_START / PAMERAN_END -> Change to DATE
--    NOTE: Direct ALTER from TIME to DATE fails. We will DROP and RE-ADD.
--    This will DELETE existing data in these columns, which is acceptable for Dev environment.
-- 2. Add Missing Columns: TANGGAL_BERDIRI, OPERATIONAL_START, OPERATIONAL_END, LUAS_TEMPAT, TIPE_BISNIS, etc.

-- 1. Modify PAMERAN_START/END to DATE
-- Strategy: Drop Constraint -> Drop Column -> Add Column

DECLARE @ConstraintName NVARCHAR(MAX);
DECLARE @Sql NVARCHAR(MAX);

-- PAMERAN_START
-- Drop Constraint
SELECT @ConstraintName = name
FROM sys.default_constraints
WHERE parent_object_id = OBJECT_ID('T_ONBOARDING_MERCHANT')
AND parent_column_id = COLUMNPROPERTY(OBJECT_ID('T_ONBOARDING_MERCHANT'), 'PAMERAN_START', 'ColumnId');

IF @ConstraintName IS NOT NULL
BEGIN
    SET @Sql = 'ALTER TABLE T_ONBOARDING_MERCHANT DROP CONSTRAINT ' + @ConstraintName;
    EXEC sp_executesql @Sql;
    PRINT '✅ Dropped Default Constraint for PAMERAN_START';
END

-- Drop Column if exists with wrong type (time)
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'PAMERAN_START' AND DATA_TYPE = 'time')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT DROP COLUMN PAMERAN_START;
    PRINT '✅ Dropped old PAMERAN_START (TIME)';
END

-- Add Column as DATE
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'PAMERAN_START')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD PAMERAN_START DATE NULL;
    PRINT '✅ Added PAMERAN_START (DATE)';
END
GO

-- PAMERAN_END
DECLARE @ConstraintName2 NVARCHAR(MAX);
DECLARE @Sql2 NVARCHAR(MAX);

-- Drop Constraint
SELECT @ConstraintName2 = name
FROM sys.default_constraints
WHERE parent_object_id = OBJECT_ID('T_ONBOARDING_MERCHANT')
AND parent_column_id = COLUMNPROPERTY(OBJECT_ID('T_ONBOARDING_MERCHANT'), 'PAMERAN_END', 'ColumnId');

IF @ConstraintName2 IS NOT NULL
BEGIN
    SET @Sql2 = 'ALTER TABLE T_ONBOARDING_MERCHANT DROP CONSTRAINT ' + @ConstraintName2;
    EXEC sp_executesql @Sql2;
    PRINT '✅ Dropped Default Constraint for PAMERAN_END';
END

-- Drop Column if exists with wrong type (time)
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'PAMERAN_END' AND DATA_TYPE = 'time')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT DROP COLUMN PAMERAN_END;
    PRINT '✅ Dropped old PAMERAN_END (TIME)';
END

-- Add Column as DATE
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'PAMERAN_END')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD PAMERAN_END DATE NULL;
    PRINT '✅ Added PAMERAN_END (DATE)';
END
GO


-- 2. Add Missing Columns (Safe idempotent checks)

-- BENTUK_USAHA_LAINNYA
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'BENTUK_USAHA_LAINNYA')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD BENTUK_USAHA_LAINNYA NVARCHAR(150) NULL;
    PRINT '✅ Added BENTUK_USAHA_LAINNYA';
END
GO

-- LINGKUNGAN_USAHA_LAINNYA
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'LINGKUNGAN_USAHA_LAINNYA')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD LINGKUNGAN_USAHA_LAINNYA NVARCHAR(150) NULL;
    PRINT '✅ Added LINGKUNGAN_USAHA_LAINNYA';
END
GO

-- STATUS_TEMPAT_LAINNYA
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'STATUS_TEMPAT_LAINNYA')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD STATUS_TEMPAT_LAINNYA NVARCHAR(150) NULL;
    PRINT '✅ Added STATUS_TEMPAT_LAINNYA';
END
GO

-- TIPE_BISNIS
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'TIPE_BISNIS')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD TIPE_BISNIS NVARCHAR(100) NULL;
    PRINT '✅ Added TIPE_BISNIS';
END
GO

-- LUAS_TEMPAT
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'LUAS_TEMPAT')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD LUAS_TEMPAT DECIMAL(10, 2) NULL;
    PRINT '✅ Added LUAS_TEMPAT';
END
GO

-- TANGGAL_BERDIRI
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'TANGGAL_BERDIRI')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD TANGGAL_BERDIRI DATE NULL;
    PRINT '✅ Added TANGGAL_BERDIRI';
END
GO

-- OPERATIONAL_START
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'OPERATIONAL_START')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD OPERATIONAL_START TIME(0) NULL;
    PRINT '✅ Added OPERATIONAL_START';
END
GO

-- OPERATIONAL_END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'OPERATIONAL_END')
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT ADD OPERATIONAL_END TIME(0) NULL;
    PRINT '✅ Added OPERATIONAL_END';
END
GO

PRINT '✅ Step 2 Schema Refinement Completed';
