USE TaspenOnboardingMerchantDB;
GO

-- Add KODE_SALES column to T_ONBOARDING_MERCHANT
IF NOT EXISTS (
  SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'T_ONBOARDING_MERCHANT' AND COLUMN_NAME = 'KODE_SALES'
)
BEGIN
    ALTER TABLE T_ONBOARDING_MERCHANT
    ADD KODE_SALES VARCHAR(50) NULL DEFAULT NULL;
    PRINT '✅ Column KODE_SALES added to T_ONBOARDING_MERCHANT';
END
ELSE
BEGIN
    PRINT 'ℹ️ Column KODE_SALES already exists';
END
GO
