-- Database Schema v3 (Master): Consolidated Schema with all FIXES
-- Run this script on your EXTERNAL SQL Server instance to create a fresh DB.
-- This script is RE-RUNNABLE (it drops existing tables first).

-- 1. Create Database if not exists
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TaspenOnboardingMerchantDB')
BEGIN
    CREATE DATABASE TaspenOnboardingMerchantDB;
END
GO

USE TaspenOnboardingMerchantDB;
GO

-- 2. Drop Tables (In correct order to avoid Foreign Key errors)
-- Drop Child Tables First
IF OBJECT_ID('T_ONBOARDING_DOCUMENT', 'U') IS NOT NULL DROP TABLE T_ONBOARDING_DOCUMENT;
IF OBJECT_ID('T_ONBOARDING_FINTECH', 'U') IS NOT NULL DROP TABLE T_ONBOARDING_FINTECH;
IF OBJECT_ID('T_ONBOARDING_MERCHANT', 'U') IS NOT NULL DROP TABLE T_ONBOARDING_MERCHANT;
-- Then Drop Parent Table
IF OBJECT_ID('T_ONBOARDING_REGISTRATION', 'U') IS NOT NULL DROP TABLE T_ONBOARDING_REGISTRATION;
-- Also Drop OTP Table
IF OBJECT_ID('otp_codes', 'U') IS NOT NULL DROP TABLE otp_codes;

-- 3. Re-Create Tables

-- Table 1: Registration Process Metadata (Parent)
CREATE TABLE T_ONBOARDING_REGISTRATION (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    REG_ID INT NULL DEFAULT NULL,
    TIPE_NASABAH VARCHAR(50) NULL DEFAULT NULL,
    TIPE_QRIS VARCHAR(50) NULL DEFAULT NULL,
    STATUS VARCHAR(50) NULL DEFAULT NULL,
    CURRENT_STEP INT NULL DEFAULT NULL,
    CREATED_AT DATETIME NULL DEFAULT GETDATE(),
    CREATED_BY VARCHAR(100) NULL DEFAULT NULL,
    UPDATED_AT DATETIME NULL DEFAULT NULL,
    UPDATED_BY VARCHAR(100) NULL DEFAULT NULL,
    IS_DELETED INT NULL DEFAULT 0
);

-- Table 2: Merchant and Owner Details
CREATE TABLE T_ONBOARDING_MERCHANT (
    REG_ID INT NULL DEFAULT NULL,
    JENIS_ID VARCHAR(50) NULL DEFAULT NULL,
    NO_ID VARCHAR(50) NULL DEFAULT NULL,
    NAMA_OWNER NVARCHAR(150) NULL DEFAULT NULL,
    NO_TLP_OWNER VARCHAR(50) NULL DEFAULT NULL,
    NPWP_OWNER VARCHAR(50) NULL DEFAULT NULL,
    
    -- Owner Address (Expanded to VARCHAR(100) or more based on fixes)
    ALAMAT_OWNER NVARCHAR(255) NULL DEFAULT NULL,
    PROVINSI_ID VARCHAR(100) NULL DEFAULT NULL,
    KOTA_ID VARCHAR(100) NULL DEFAULT NULL,
    KELURAHAN_ID VARCHAR(100) NULL DEFAULT NULL,
    KECAMATAN_ID VARCHAR(100) NULL DEFAULT NULL,
    RT_ID VARCHAR(10) NULL DEFAULT NULL,
    RW_ID VARCHAR(10) NULL DEFAULT NULL,
    KODEPOS_ID VARCHAR(10) NULL DEFAULT NULL,
    
    -- Merchant Details
    NAMA_MERCHANT NVARCHAR(200) NULL DEFAULT NULL,
    NAMA_MERCHANT_QR NVARCHAR(100) NULL DEFAULT NULL,
    EMAIL_MERCHANT VARCHAR(100) NULL DEFAULT NULL,
    
    -- Merchant Address (Expanded)
    ALAMAT_MERCHANT NVARCHAR(255) NULL DEFAULT NULL,
    PROVINSI_MERCHANT VARCHAR(100) NULL DEFAULT NULL,
    KOTA_MERCHANT VARCHAR(100) NULL DEFAULT NULL,
    KELURAHAN_MERCHANT VARCHAR(100) NULL DEFAULT NULL,
    KECAMATAN_MERCHANT VARCHAR(100) NULL DEFAULT NULL,
    RT_MERCHANT VARCHAR(10) NULL DEFAULT NULL,
    RW_MERCHANT VARCHAR(10) NULL DEFAULT NULL,
    KODEPOS_MERCHANT VARCHAR(10) NULL DEFAULT NULL,
    
    -- Business Profile
    BENTUK_USAHA VARCHAR(100) NULL DEFAULT NULL,
    BENTUK_USAHA_LAINNYA NVARCHAR(150) NULL DEFAULT NULL,
    PAMERAN_START TIME(0) NULL DEFAULT NULL,
    PAMERAN_END TIME(0) NULL DEFAULT NULL,
    BIDANG_USAHA VARCHAR(100) NULL DEFAULT NULL,
    JENIS_PRODUK NVARCHAR(200) NULL DEFAULT NULL,
    TIPE_BISNIS NVARCHAR(100) NULL DEFAULT NULL,
    NO_TLP_MERCHANT VARCHAR(50) NULL DEFAULT NULL,
    SOSIAL_MEDIA NVARCHAR(150) NULL DEFAULT NULL,
    LINGKUNGAN_USAHA VARCHAR(100) NULL DEFAULT NULL,
    LINGKUNGAN_USAHA_LAINNYA NVARCHAR(150) NULL DEFAULT NULL,
    STATUS_TEMPAT VARCHAR(100) NULL DEFAULT NULL,
    STATUS_TEMPAT_LAINNYA NVARCHAR(150) NULL DEFAULT NULL,
    LUAS_TEMPAT DECIMAL(10, 2) NULL DEFAULT NULL,
    TANGGAL_BERDIRI DATE NULL DEFAULT NULL,
    OPERATIONAL_START TIME(0) NULL DEFAULT NULL,
    OPERATIONAL_END TIME(0) NULL DEFAULT NULL,
    JUMLAH_KARYAWAN INT NULL DEFAULT NULL,
    
    -- PIC Details
    PIC1_NAMA NVARCHAR(150) NULL DEFAULT NULL,
    PIC1_TLP VARCHAR(50) NULL DEFAULT NULL,
    PIC2_NAMA NVARCHAR(150) NULL DEFAULT NULL,
    PIC2_TLP VARCHAR(50) NULL DEFAULT NULL,
    
    IS_DELETED INT NULL DEFAULT 0,
    FOREIGN KEY (REG_ID) REFERENCES T_ONBOARDING_REGISTRATION(ID)
);

-- Table 3: Financial and Bank Information
CREATE TABLE T_ONBOARDING_FINTECH (
    REG_ID INT NULL DEFAULT NULL,
    
    -- Expanded all critical columns to VARCHAR(100) or VARCHAR(50)
    BANK_CODE VARCHAR(50) NULL DEFAULT NULL,
    NO_REKENING VARCHAR(50) NULL DEFAULT NULL,
    NAMA_REKENING NVARCHAR(150) NULL DEFAULT NULL,
    TIPE_REKENING VARCHAR(50) NULL DEFAULT NULL,
    KODE_CABANG VARCHAR(100) NULL DEFAULT NULL, 
    STATUS_KEPEMILIKAN VARCHAR(50) NULL DEFAULT NULL,
    
    SALES_VOLUME_TAHUN DECIMAL(18, 2) NULL DEFAULT NULL,
    AVG_TRANSAKSI DECIMAL(18, 2) NULL DEFAULT NULL,
    KOMITMENT_BULANAN DECIMAL(18, 2) NULL DEFAULT NULL,
    SALDO_MENGENDAP DECIMAL(18, 2) NULL DEFAULT NULL,
    ESTIMASI_FREKUENSI INT NULL DEFAULT NULL,
    
    KC_AKUISISI VARCHAR(100) NULL DEFAULT NULL,
    KC_LOKASI VARCHAR(100) NULL DEFAULT NULL,
    MCC_CODE VARCHAR(50) NULL DEFAULT NULL,
    KATEGORI_USAHA VARCHAR(100) NULL DEFAULT NULL,
    
    MDR DECIMAL(5, 2) NULL DEFAULT NULL,
    SETTLEMENT_HARI TINYINT NULL DEFAULT NULL,
    JUMLAH_QR SMALLINT NULL DEFAULT NULL,
    JUMLAH_EDC SMALLINT NULL DEFAULT NULL,
    EDC_BANK_LAIN NVARCHAR(150) NULL DEFAULT NULL,
    EDC_FEE DECIMAL(18, 2) NULL DEFAULT NULL,
    
    IS_DELETED INT NULL DEFAULT 0,
    FOREIGN KEY (REG_ID) REFERENCES T_ONBOARDING_REGISTRATION(ID)
);

-- Table 4: Document Uploads
CREATE TABLE T_ONBOARDING_DOCUMENT (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    REG_ID INT NULL DEFAULT NULL,
    DOC_TYPE VARCHAR(100) NULL DEFAULT NULL,
    DOC_TITLE NVARCHAR(200) NULL DEFAULT NULL,
    FILE_PATH NVARCHAR(500) NULL DEFAULT NULL,
    FILE_SIZE INT NULL DEFAULT NULL,
    UPLOADED_AT DATETIME NULL DEFAULT GETDATE(),
    IS_DELETED INT NULL DEFAULT 0,
    FOREIGN KEY (REG_ID) REFERENCES T_ONBOARDING_REGISTRATION(ID)
);

-- OTP Table
CREATE TABLE otp_codes (
    id INT IDENTITY(1,1) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    otp_code VARCHAR(10) NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
    expires_at DATETIME,
    used BIT DEFAULT 0
);

PRINT 'Schema v3 (Consolidated) re-created successfully! Ready for External/Dev usage.';
GO
