-- Paste SQL T_TIPE_BISNIS Anda di sini
IF OBJECT_ID('dbo.[T_TIPE_BISNIS]', 'U') IS NOT NULL DROP TABLE [T_TIPE_BISNIS];
GO

CREATE TABLE [T_TIPE_BISNIS] (
    [ID]	INT,
    [TIPE_BISNIS]	VARCHAR(512)
);

INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1001', 'Biro Perjalanan  -  Haji, Umroh, Perjalanan Rohani & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1002', 'Biro Perjalanan  -  Wisata, Pesiar & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1003', 'F&B  -  Cafe, Bar, Lounge & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1004', 'F&B  -  Makanan Cepat Saji');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1005', 'F&B  -  Restaurant');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1006', 'Fashion  -  Baju, Celana & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1007', 'Fashion  -  Butik');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1008', 'Fashion  -  Department Stores');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1009', 'Fashion  -  Factory Outlet');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1010', 'Fashion  -  Laundry, Dry Clean & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1011', 'Fashion  -  Penjahit, Taylor & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1012', 'Fashion  -  Perlengkapan Bayi, Anak & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1013', 'Fashion  -  Sepatu, Sendal & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1014', 'Fashion  -  Seragam, Sprei & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1015', 'Fashion  -  Sulaman, Bordir & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1016', 'Fashion  -  Tas, Koper & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1017', 'Fashion  -  Textile, Kain & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1018', 'Fun & Leisure  -  Bioskop, Theatre & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1019', 'Fun & Leisure  -  Fitness Center, Pusat Kebugaran & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1020', 'Fun & Leisure  -  Refleksi, Spa, Massage & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1021', 'Fun & Leisure  -  Taman Wisata, Taman Bermain, Game Center & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1022', 'Jasa  -  Advertising');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1023', 'Jasa  -  Dekorasi Interior, Dekorasi Eksterior & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1024', 'Jasa  -  Digital Printing');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1025', 'Jasa  -  Event Organizer');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1026', 'Jasa  -  Jasa Penerbangan Komersial, Carter & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1027', 'Jasa  -  Konsultan Hukum, Konsultan Keuangan & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1028', 'Jasa  -  Koperasi & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1029', 'Jasa  -  Logistik, Kiriman Barang & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1030', 'Jasa  -  Pegadaian, Pos & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1031', 'Jasa  -  Pembayaran Listrik, Air, Telepon Dll');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1032', 'Jasa  -  Penerbangan Komersil_Carter Dsb');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1033', 'Jasa  -  ProvIDer Internet, Tv Berlangganan & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1034', 'Jasa  -  Rental Motor, Mobil, Bus & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1035', 'Jasa  -  Studio Foto');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1036', 'Jasa  -  Studio Musik');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1037', 'Jasa  -  Tv Kabel');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1038', 'Jasa  -  Warnet, Wartel & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1039', 'Kendaraan  -  Dealer Kendaraan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1040', 'Kendaraan  -  Pencucian Kendaraan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1041', 'Kendaraan  -  Sparepart & Service Mobil');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1042', 'Kendaraan  -  Sparepart & Service Motor');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1043', 'Kendaraan  -  Spbu');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1044', 'Keuangan  -  Asuransi');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1045', 'Keuangan  -  Bank');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1046', 'Keuangan  -  Money Changer');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1047', 'Medical  -  Apotik, Toko Farmasi & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1048', 'Medical  -  Dokter Praktek Pribadi, Umum, Gigi & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1049', 'Medical  -  Klinik');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1050', 'Medical  -  Laboratorium');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1051', 'Medical  -  Optik, Lensa & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1052', 'Medical  -  Peralatan Farmasi');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1053', 'Medical  -  Peralatan Kesehatan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1054', 'Medical  -  Poli Klinik');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1055', 'Medical  -  Rumah Sakit');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1056', 'Miscellaneous Food Stores - Convenience Storesspecialty Markets');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1057', 'PendIDikan  -  Bimbingan Belajar');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1058', 'PendIDikan  -  Perguruan Tinggi');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1059', 'PendIDikan  -  Sekolah Musik');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1060', 'PendIDikan  -  Sekolah Umum');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1061', 'PendIDikan  -  Training Center');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1062', 'Penginapan  -  Hotel Bintang 1');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1063', 'Penginapan  -  Hotel Bintang 2');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1064', 'Penginapan  -  Hotel Bintang 3');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1065', 'Penginapan  -  Hotel Bintang 4');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1066', 'Penginapan  -  Hotel Bintang 5');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1067', 'Penginapan  -  Hotel Melati');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1068', 'Penginapan  -  Resort, Villa, Wisma, Motel & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1069', 'Produk  -  Alat Musik & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1070', 'Produk  -  Alat Teknik & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1071', 'Produk  -  Alat Tulis Kantor & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1072', 'Produk  -  Bahan Bakar Gas, Lpg, Minyak Dll');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1073', 'Produk  -  Bahan Bangunan, Semen & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1074', 'Produk  -  Barang Antik, Lukisan, Kesenian & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1075', 'Produk  -  Besi, Baja, Aluminium & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1076', 'Produk  -  Buku,Alat Tulis Kantor & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1077', 'Produk  -  Emas, Berlian, Permata, Perhiasan, Lm & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1078', 'Produk  -  Gadget, Hp, Tablet, Smartphone, Accessories & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1079', 'Produk  -  Jam Tangan & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1080', 'Produk  -  Kamera, Accessories & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1081', 'Produk  -  Kaset, Cd, Dvd & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1082', 'Produk  -  Koleksi, Hobby, Mainan, Olahraga, Hewan Peliharaan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1083', 'Produk  -  Komputer, Services, Accessories & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1084', 'Produk  -  Koperasi & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1085', 'Produk  -  Multi Level Marketing & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1086', 'Produk  -  Oleh - Oleh & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1087', 'Produk  -  Parfum, Aroma Therapy & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1088', 'Produk  -  Peralatan Listrik & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1089', 'Produk  -  Peralatan Rumah Tangga & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1090', 'Produk  -  Perlengkapan Salon Kecantikan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1091', 'Produk  -  Perlengkapan Sekolah & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1092', 'Produk  -  Pertanian, Perkebunan, Perikanan & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1093', 'Produk  -  Plastik, Acrylic & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1094', 'Produk  -  Property Dan Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1095', 'Produk  -  Sembako, Kelontong & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1096', 'Produk  -  Tv, Radio, Barang Elektronik & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1097', 'Produk  -  Wallpaper, Karpet & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1098', 'Pusat Belanja  -  Minimarket, Convenience Store & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1099', 'Pusat Belanja  -  Supermarket');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1100', 'Pusat Belanja  -  Swalayan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1101', 'Pusat Belanja  -  Toserba');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1102', 'Salon  -  Perlengkapan Kosmetik');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1103', 'Salon  -  Salon Kecantikan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1104', 'Yayasan  -  Sosial, Panti, Yatim Piatu, Agama & Semacamnya');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1105', 'Lainnya  -  Biro Perjalanan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1106', 'Lainnya  -  F&B');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1107', 'Lainnya  -  Fashion');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1108', 'Lainnya  -  Fun & Leisure');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1109', 'Lainnya  -  Jasa');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1110', 'Lainnya  -  Kendaraan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1111', 'Lainnya  -  Keuangan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1112', 'Lainnya  -  Medical');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1113', 'Lainnya  -  PendIDikan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1114', 'Lainnya  -  Penginapan');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1115', 'Lainnya  -  Produk');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1116', 'Lainnya  -  Pusat Belanja');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1117', 'Lainnya  -  Salon');
INSERT INTO [T_TIPE_BISNIS] ([ID], [TIPE_BISNIS]) VALUES ('1118', 'Lainnya  -  Yayasan');
